apiVersion: v2
name: grafana-wrapper
description: Local wrapper chart for Grafana deployment via upstream chart
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
