# Grafana DEV overrides
replicas: 1
initChownData:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi

persistence:
  storageClassName: local-path
  size: 1Gi

ingress:
  hosts:
    - grafana.alloysoftware.us
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.alloysoftware.us

grafana.ini:
  server:
    root_url: https://grafana.alloysoftware.us
