apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring-certificates.yaml
  - grafana.yaml
  - grafana-dashboards.yaml
  - victoria-metrics.yaml
  - victoria-logs.yaml
